from formulaBuilder.AtomBuildingStrategy import AtomBuildingStrategy
EXPERIMENTS_FOLDER = "experiments/"
DT_DECREASE_RATE = 0.5
DT_SAMPLING_STRATEGY = AtomBuildingStrategy.CHOOSE_NOT_SEPARATED
DT_RESTARTS_OF_SAMPLING = 3
DT_REPETITIONS_INSIDE_SAMPLING = 3
DT_SUBSET_SIZE = 3